man_finance_homepage:
    pattern:  /
    defaults: { _controller: ManFinanceBundle:Default:index }

man_finance_test:
    pattern:  /test
    defaults: { _controller: ManFinanceBundle:Default:test }

man_finance_dec:
    resource: "@ManFinanceBundle/Resources/config/routing/dec.yml"
    prefix:   /finance/dec

man_finance_customer:
    resource: "@ManFinanceBundle/Resources/config/routing/customer.yml"
    prefix:   /finance/customer

man_finance_address:
        resource: "@ManFinanceBundle/Resources/config/routing/address.yml"
        prefix:   /finance/address
#finance/dec
