man_finance_homepage:
    pattern:  /
    defaults: { _controller: ManFinanceBundle:Default:index }

man_finance_test:
    pattern:  /test
    defaults: { _controller: ManFinanceBundle:Default:test }

man_finance_dec:
    resource: "@ManFinanceBundle/Resources/config/routing/dec.yml"
    prefix:   /finance/dec

man_finance_customer:
    resource: "@ManFinanceBundle/Resources/config/routing/customer.yml"
    prefix:   /finance/customer

man_finance_address:
        resource: "@ManFinanceBundle/Resources/config/routing/address.yml"
        prefix:   /finance/address

ManFinanceBundle_finance_branch:
    resource: "@ManFinanceBundle/Resources/config/routing/branch.yml"
    prefix:   /finance/branch

ManFinanceBundle_finance_owner:
        resource: "@ManFinanceBundle/Resources/config/routing/owner.yml"
        prefix:   /finance/owner

ManFinanceBundle_finance_card:
        resource: "@ManFinanceBundle/Resources/config/routing/card.yml"
        prefix:   /finance/card