parameters:
#    man_finance.example.class: Man\FinanceBundle\Example

services:
#    man_finance.example:
#        class: %man_finance.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
