man_finance_dec_new:
    pattern:  /new
    defaults: { _controller: ManFinanceBundle:Dec:new }

man_finance_dec_create:
    pattern:  /create
    defaults: { _controller: ManFinanceBundle:Dec:create }

man_finance_dec_searchcard:
    pattern:  /searchcard
    defaults: { _controller: ManFinanceBundle:Default:test }

man_finance_dec_debtsmem:
    pattern:  /debtsmem
    defaults: { _controller: ManFinanceBundle:Default:test }

man_finance_dec_debtsarea:
    pattern:  /debtsarea
    defaults: { _controller: ManFinanceBundle:Default:test }

man_finance_dec_appointment:
    pattern:  /appointment
    defaults: { _controller: ManFinanceBundle:Default:test }

man_finance_dec_percentdebt:
    pattern:  /percentdebt
    defaults: { _controller: ManFinanceBundle:Default:test }