# src/Man/FinanceBundle/Resources/config/doctrine/Card.orm.yml
Man\FinanceBundle\Entity\Card:
  type: entity
  table: man_card
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    display_id:
      type: string
      length: 255
      unique: true
    card_type:
      type: string
      length: 255
      unique: false	  
      nullable: true	
    employee_id:
      type: integer 	
    mid:
      type: string
      length: 255
      unique: false	  
      nullable: true	
    branch_id:
      type: integer
    begin_cost:
      type: string
      length: 255
      nullable: true		  
    card_status:
      type: string
      length: 255
      nullable: true	
    contract_style:
      type: string
      length: 255
      nullable: true	
    contract_date:
      type: date
      nullable: true	 	  
    finish_contract_date:
      type: date
      nullable: true	 	  
    cycle_day:
      type: string
      length: 255
      nullable: true		
    interest_percent:
      type: string
      length: 255
      nullable: true
    interest_late_percent:
      type: string
      length: 255
      nullable: true	
    allow_day_late:
      type: string
      length: 255
      nullable: true
    last_payment_date:
      type: date
      nullable: true	 
    next_payment_date:
      type: date
      nullable: true	 
    current_due_date:
      type: date
      nullable: true	 		  	  
    next_due_date:
      type: date
      nullable: true	 		  
    current_cost:
      type: string
      length: 255
      nullable: true
    current_interest:
      type: string
      length: 255
      nullable: true	  
    current_fine:
      type: string
      length: 255
      nullable: true	
    ip_address:
      type: string
      length: 255
      nullable: true	
    is_deleted:
      type: boolean
      nullable: true	  
    created_at:
      type: datetime
      nullable: true		
    update_at:
      type: datetime
      nullable: true		  	  	    	  	    	   	      
    note:
      type: text
      nullable: true		  	  	    	  	    	   	      
  oneToMany:
    card_customer:
      targetEntity: CardCustomer
      mappedBy: card
    card_supporter:
      targetEntity: CardSupporter
      mappedBy: card
    card_property_car:
      targetEntity: CardPropertyCar
      mappedBy: card	  
    card_property_land:
      targetEntity: CardPropertyLand
      mappedBy: card
    card_document:
      targetEntity: CardDocument
      mappedBy: card	 	
    card_finance:
      targetEntity: CardFinance
      mappedBy: card	 
    card_effective:
      targetEntity: CardEffective
      mappedBy: card	
    receipt_card:
      targetEntity: ReceiptCard
      mappedBy: card  	  
  manyToOne:
    branch:
      targetEntity: Branch
      inversedBy: man_card
      joinColumn:
        name: branch_id
        referencedColumnName: id	
    employee:
      targetEntity: Employee
      inversedBy: man_card
      joinColumn:
        name: employee_id
        referencedColumnName: id
    owner:
      targetEntity: Owner
      inversedBy: man_card
      joinColumn:
        name: owner_id
        referencedColumnName: id						  	  	    
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]