acme_task_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeTaskBundle:Default:index }

acme_task_newform:
    pattern:  /new
    defaults: { _controller: AcmeTaskBundle:Task:new }